import { Song, TeamMember, WorshipEvent } from '../types';

export const INITIAL_EVENTS: WorshipEvent[] = [
  {
    id: '1',
    title: 'Culto de Celebração',
    date: '2026-04-05',
    time: '19:00',
    type: 'service',
    location: 'Igreja Manancial',
    songs: ['9e17bfe9-f4df-4265-80fc-357943d6589d', '5de1a0df-7aeb-48a8-bf66-f6b146cc9289', 'c5f94321-486f-48d6-91e6-759c49f4575d', 'ceab9ac0-b8a4-448d-8e18-65befa54a150'],
    outroSongs: ['be30a782-6cd3-41da-a12f-38165667b8d4'],
    team: {
      vocal: ['Elaine', 'Janaina', 'Silvia'],
      instruments: {
        'Violão': 'Lucas Bombo',
        Guitarra: 'Paulinho',
        Baixo: 'Carlinhos',
        Bateria: 'Alexandre',
        Teclado: 'Caio',
      },
    },
  },
  {
    id: '2',
    title: 'Ensaio Geral',
    date: '2026-04-04',
    time: '15:00',
    type: 'rehearsal',
    location: 'Igreja Manancial',
    songs: ['9e17bfe9-f4df-4265-80fc-357943d6589d', '5de1a0df-7aeb-48a8-bf66-f6b146cc9289', 'c5f94321-486f-48d6-91e6-759c49f4575d', 'ceab9ac0-b8a4-448d-8e18-65befa54a150', 'e7dca790-78cd-4d50-917b-703b3398ff31', '13c6cd91-9d95-4548-8f3a-81b9fa4d8d93'],
    outroSongs: [],
    team: {
      vocal: ['Elaine', 'Janaina', 'Pamela', 'Silvia'],
      instruments: {
        'Violão': 'Lucas Bombo',
        Guitarra: 'Paulinho',
        Baixo: 'Carlinhos',
        Bateria: 'Alexandre',
        Teclado: 'Caio',
      },
    },
  },
  {
    id: '3',
    title: 'Culto de Santa Ceia',
    date: '2026-04-12',
    time: '18:30',
    type: 'service',
    location: 'Igreja Manancial',
    songs: ['5de1a0df-7aeb-48a8-bf66-f6b146cc9289', 'f9a308dd-40bd-484d-a297-7ba47400b6ba', '498eb0b2-df1c-45f1-be21-8cc9da7ff1dc', 'a2f3cb45-7363-4794-9b43-c26be5f948e8'],
    outroSongs: ['c5f94321-486f-48d6-91e6-759c49f4575d'],
    team: {
      vocal: ['Pamela', 'Silvia'],
      instruments: {
        'Violão': 'Pedro Smanioto',
        Guitarra: 'Paulinho',
        Baixo: 'Carlinhos',
        Bateria: 'Alexandre',
        Teclado: 'Caio',
      },
    },
  },
  {
    id: '4',
    title: 'Ensaio Vocais',
    date: '2026-04-11',
    time: '14:00',
    type: 'rehearsal',
    location: 'Igreja Manancial',
    songs: ['5de1a0df-7aeb-48a8-bf66-f6b146cc9289', 'f9a308dd-40bd-484d-a297-7ba47400b6ba', '498eb0b2-df1c-45f1-be21-8cc9da7ff1dc', 'a2f3cb45-7363-4794-9b43-c26be5f948e8'],
    outroSongs: [],
    team: {
      vocal: ['Elaine', 'Janaina', 'Pamela', 'Silvia'],
      instruments: {},
    },
  },
];

export const INITIAL_SONGS: Song[] = [
  { id: '9e17bfe9-f4df-4265-80fc-357943d6589d', title: 'Mil Graus', artist: 'Renascer Praise', key: 'C', proficiency: 4, difficulty: 4, tags: ['Celebracao'], links: { chords: 'https://www.cifraclub.com.br/renascer-praise/mil-graus/', lyrics: 'https://www.letras.mus.br/renascer-praise/mil-graus/' }, isFavorite: true },
  { id: '5de1a0df-7aeb-48a8-bf66-f6b146cc9289', title: 'Atrai-me, Coracao', artist: 'Ministerio Zoe', key: 'C', proficiency: 5, difficulty: 3, tags: ['Adoracao'], links: { chords: 'https://www.cifraclub.com.br/ministerio-zoe/atrai-me-coracao/', lyrics: 'https://www.letras.mus.br/ministerio-zoe/atrai-me-coracao/' } },
  { id: 'c5f94321-486f-48d6-91e6-759c49f4575d', title: 'Digno de Tudo', artist: 'Central 3', key: 'C', proficiency: 5, difficulty: 3, tags: ['Adoracao'], links: { chords: 'https://www.cifraclub.com.br/central-3/digno-de-tudo/', lyrics: 'https://www.letras.mus.br/central-3/digno-de-tudo/' } },
  { id: '48262825-ee28-4659-8b5e-946946c4c69b', title: 'Te Exaltamos', artist: 'Cassiane', key: 'C', proficiency: 3, difficulty: 3, tags: ['Celebracao'], links: { chords: 'https://www.cifraclub.com.br/cassiane/te-exaltamos/', lyrics: 'https://www.letras.mus.br/cassiane/te-exaltamos/' } },
  { id: 'f9a308dd-40bd-484d-a297-7ba47400b6ba', title: 'Minhas Lamparinas', artist: 'Ministerio Zoe', key: 'C', proficiency: 4, difficulty: 4, tags: ['Adoracao'], links: { chords: 'https://www.cifraclub.com.br/ministerio-zoe/minhas-lamparinas/', lyrics: 'https://www.letras.mus.br/ministerio-zoe/minhas-lamparinas/' } },
  { id: 'ceab9ac0-b8a4-448d-8e18-65befa54a150', title: 'Santo pra Sempre', artist: 'Gabriel Guedes', key: 'C', proficiency: 5, difficulty: 3, tags: ['Adoracao'], links: { chords: 'https://www.cifraclub.com.br/gabriel-guedes/santo-pra-sempre/', lyrics: 'https://www.letras.mus.br/gabriel-guedes/santo-pra-sempre/' } },
  { id: 'be30a782-6cd3-41da-a12f-38165667b8d4', title: 'Eu Sou Livre', artist: 'Fernandinho', key: 'C', proficiency: 4, difficulty: 4, tags: ['Celebracao'], links: { chords: 'https://www.cifraclub.com.br/fernandinho/eu-sou-livre/', lyrics: 'https://www.letras.mus.br/fernandinho/eu-sou-livre/' } },
  { id: '1e839901-87fa-4b3f-9baa-541cffdb0222', title: 'Nada Temerei', artist: 'Igreja Batista Atitude', key: 'C', proficiency: 3, difficulty: 3, tags: ['Adoracao'], links: { chords: 'https://www.cifraclub.com.br/igreja-batista-atitude/nada-temerei/', lyrics: 'https://www.letras.mus.br/igreja-batista-atitude/nada-temerei/' } },
  { id: '0a4a2a09-3bea-4020-9502-379a852e34e2', title: 'Sublime', artist: 'Leonardo Goncalves', key: 'D', proficiency: 2, difficulty: 5, tags: ['Adoracao'], links: { chords: 'https://www.cifraclub.com.br/leonardo-goncalves/sublime/', lyrics: 'https://www.letras.mus.br/leonardo-goncalves/sublime/' } },
  { id: 'e7dca790-78cd-4d50-917b-703b3398ff31', title: 'Poderoso Deus', artist: 'Antonio Cirilo', key: 'D', proficiency: 5, difficulty: 2, tags: ['Adoracao'], links: { chords: 'https://www.cifraclub.com.br/antonio-cirilo/poderoso-deus/', lyrics: 'https://www.letras.mus.br/antonio-cirilo/poderoso-deus/' } },
  { id: '07b42716-d805-491c-9441-34425e47129c', title: 'Gratidao', artist: 'Ministerio Sarando a Terra Ferida', key: 'D', proficiency: 4, difficulty: 3, tags: ['Adoracao'], links: { chords: 'https://www.cifraclub.com.br/ministerio-sarando-terra-ferida/gratidao/', lyrics: 'https://www.letras.mus.br/ministerio-sarando-terra-ferida/gratidao/' } },
  { id: '94ce2896-e75c-4217-b89c-a91e1712ca40', title: 'Ressuscita', artist: 'Ministerio Ipiranga', key: 'D', proficiency: 4, difficulty: 4, tags: ['Adoracao'], links: { chords: 'https://www.cifraclub.com.br/ministerio-ipiranga/ressuscita/', lyrics: 'https://www.letras.mus.br/ministerio-ipiranga/ressuscita/' } },
  { id: '13c6cd91-9d95-4548-8f3a-81b9fa4d8d93', title: 'Vencendo Vem Jesus', artist: 'Harpa Crista', key: 'D', proficiency: 5, difficulty: 3, tags: ['Celebracao'], links: { chords: 'https://www.cifraclub.com.br/harpa-crista/vencendo-vem-jesus/', lyrics: 'https://www.letras.mus.br/harpa-crista/vencendo-vem-jesus/' } },
  { id: '0a52138b-3a9a-43c0-8b52-460497e58750', title: 'Aquele que Esta Feliz', artist: 'Comunidade da Zona Sul', key: 'E', proficiency: 5, difficulty: 4, tags: ['Celebracao'], links: { chords: 'https://www.cifraclub.com.br/comunidade-evangelica-internacional-da-zona-sul/aquele-que-esta-feliz/', lyrics: 'https://www.letras.mus.br/comunidade-evangelica-internacional-da-zona-sul/aquele-que-esta-feliz/' } },
  { id: 'aace0e41-b2c2-4817-ab81-ded311c13a5f', title: 'E Bom Estarmos Aqui Louvando a Deus', artist: 'Corinhos Evangelicos', key: 'E', proficiency: 5, difficulty: 3, tags: ['Celebracao'], links: { chords: 'https://www.cifraclub.com.br/corinhos-evangelicos/e-bom-estarmos-aqui/', lyrics: 'https://www.letras.mus.br/corinhos-evangelicos/e-bom-estarmos-aqui/' } },
  { id: 'cfe45c57-e41e-4231-8ea0-0f8445c104d3', title: 'Diante de Ti', artist: 'Quatro por Um', key: 'E', proficiency: 4, difficulty: 3, tags: ['Adoracao'], links: { chords: 'https://www.cifraclub.com.br/quatro-por-um/diante-de-ti/', lyrics: 'https://www.letras.mus.br/quatro-por-um/diante-de-ti/' } },
  { id: '720da98c-0770-4f72-902b-c2b4ad6cf5c5', title: 'Ate que o Senhor Venha', artist: 'Ministerio Ipiranga', key: 'E', proficiency: 3, difficulty: 4, tags: ['Adoracao'], links: { chords: 'https://www.cifraclub.com.br/ministerio-ipiranga/ate-que-o-senhor-venha/', lyrics: 'https://www.letras.mus.br/ministerio-ipiranga/ate-que-o-senhor-venha/' } },
  { id: '498eb0b2-df1c-45f1-be21-8cc9da7ff1dc', title: 'Espirito, Enche a Minha Vida', artist: 'Quatro por Um', key: 'G', proficiency: 5, difficulty: 2, tags: ['Adoracao'], links: { chords: 'https://www.cifraclub.com.br/quatro-por-um/espirito-enche-minha-vida/', lyrics: 'https://www.letras.mus.br/quatro-por-um/espirito-enche-minha-vida/' } },
  { id: '54d5e7d3-b92f-450c-a005-f7c4144c03cb', title: 'So Tu Es Santo', artist: 'Morada', key: 'G', proficiency: 4, difficulty: 4, tags: ['Adoracao'], links: { chords: 'https://www.cifraclub.com.br/morada/so-tu-es-santo/', lyrics: 'https://www.letras.mus.br/morada/so-tu-es-santo/' } },
  { id: '87ae98b2-88ba-4492-94e5-ef2f5cd7d22d', title: 'Lugares Altos', artist: 'Renascer Praise', key: 'A', proficiency: 4, difficulty: 4, tags: ['Adoracao'], links: { chords: 'https://www.cifraclub.com.br/renascer-praise/lugares-altos/', lyrics: 'https://www.letras.mus.br/renascer-praise/lugares-altos/' } },
  { id: 'a2f3cb45-7363-4794-9b43-c26be5f948e8', title: 'Face Adorada', artist: 'Harpa Crista', key: 'A', proficiency: 5, difficulty: 3, tags: ['Adoracao'], links: { chords: 'https://www.cifraclub.com.br/harpa-crista/face-adorada/', lyrics: 'https://www.letras.mus.br/harpa-crista/face-adorada/' } },
  { id: '4f03917d-13d7-423a-9c8d-f0ba4f86c5fd', title: 'Galileu', artist: 'Fernandinho', key: 'Am', proficiency: 5, difficulty: 4, tags: ['Celebracao'], links: { chords: 'https://www.cifraclub.com.br/fernandinho/galileu/', lyrics: 'https://www.letras.mus.br/fernandinho/galileu/' } },
  { id: '9266394c-cbe2-40bc-81af-b577982daee2', title: 'Que Ruja o Leao', artist: 'Talita Catanzaro', key: 'C#m', proficiency: 4, difficulty: 5, tags: ['Adoracao'], links: { chords: 'https://www.cifraclub.com.br/talita-catanzaro/que-ruja-o-leao/', lyrics: 'https://www.letras.mus.br/talita-catanzaro/que-ruja-o-leao/' } },
  { id: 'eea04b3c-63c9-4356-8456-909d8b354334', title: 'Aclame ao Senhor', artist: 'Diante do Trono', key: 'G -> A', proficiency: 5, difficulty: 3, tags: ['Adoracao'], links: { chords: 'https://www.cifraclub.com.br/diante-do-trono/aclame-ao-senhor/', lyrics: 'https://www.letras.mus.br/diante-do-trono/aclame-ao-senhor/' } },
  { id: '1b18a355-b9f4-4326-a5be-48c3cbc2876a', title: 'Quem E Esse', artist: 'Ministerio Zoe', key: 'F# -> G#', proficiency: 4, difficulty: 5, tags: ['Adoracao'], links: { chords: 'https://www.cifraclub.com.br/ministerio-zoe/quem-esse/', lyrics: 'https://www.letras.mus.br/ministerio-zoe/quem-esse/' } },
];

export const INITIAL_TEAM: TeamMember[] = [
  { id: '1', name: 'Elaine', role: 'Vocal', category: 'Vocais' },
  { id: '2', name: 'Janaina', role: 'Vocal', category: 'Vocais' },
  { id: '3', name: 'Pamela', role: 'Vocal', category: 'Vocais' },
  { id: '4', name: 'Silvia', role: 'Ministra', category: 'Vocais', isLeader: true },
  { id: '5', name: 'Lucas Bombo', role: 'Violão', category: 'Violão' },
  { id: '6', name: 'Pedro Smanioto', role: 'Violão', category: 'Violão' },
  { id: '7', name: 'Paulinho', role: 'Guitarra e Voz', category: 'Guitarra' },
  { id: '8', name: 'Carlinhos', role: 'Baixo e Voz', category: 'Baixo' },
  { id: '9', name: 'Alexandre', role: 'Bateria', category: 'Bateria' },
  { id: '10', name: 'Caio', role: 'Teclado e Voz', category: 'Teclado' },
];
